config/routes.rb
Minds::Application.routes.draw do
  resources :hidden_neuron_layers

  resources :analyses

  get "welcome/hero"

  resources :training_data

  resources :minds

  root :to => 'welcome#hero'

end

app/models/hidden_neuron_layer.rb
class HiddenNeuronLayer < ActiveRecord::Base
  attr_accessible :mind_id, :neuron_count, :position
  belongs_to :mind
end

app/controllers/hidden_neuron_layers_controller.rb
class HiddenNeuronLayersController < ApplicationController
  # GET /hidden_neuron_layers
  # GET /hidden_neuron_layers.json
  def index
    @hidden_neuron_layers = HiddenNeuronLayer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hidden_neuron_layers }
    end
  end

  # GET /hidden_neuron_layers/1
  # GET /hidden_neuron_layers/1.json
  def show
    @hidden_neuron_layer = HiddenNeuronLayer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hidden_neuron_layer }
    end
  end

  # GET /hidden_neuron_layers/new
  # GET /hidden_neuron_layers/new.json
  def new
    @hidden_neuron_layer = HiddenNeuronLayer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hidden_neuron_layer }
    end
  end

  # GET /hidden_neuron_layers/1/edit
  def edit
    @hidden_neuron_layer = HiddenNeuronLayer.find(params[:id])
  end

  # POST /hidden_neuron_layers
  # POST /hidden_neuron_layers.json
  def create
    @hidden_neuron_layer = HiddenNeuronLayer.new(params[:hidden_neuron_layer])

    respond_to do |format|
      if @hidden_neuron_layer.save
        format.html { redirect_to @hidden_neuron_layer, notice: 'Hidden neuron layer was successfully created.' }
        format.json { render json: @hidden_neuron_layer, status: :created, location: @hidden_neuron_layer }
      else
        format.html { render action: "new" }
        format.json { render json: @hidden_neuron_layer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hidden_neuron_layers/1
  # PUT /hidden_neuron_layers/1.json
  def update
    @hidden_neuron_layer = HiddenNeuronLayer.find(params[:id])

    respond_to do |format|
      if @hidden_neuron_layer.update_attributes(params[:hidden_neuron_layer])
        format.html { redirect_to @hidden_neuron_layer, notice: 'Hidden neuron layer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hidden_neuron_layer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hidden_neuron_layers/1
  # DELETE /hidden_neuron_layers/1.json
  def destroy
    @hidden_neuron_layer = HiddenNeuronLayer.find(params[:id])
    @hidden_neuron_layer.destroy

    respond_to do |format|
      format.html { redirect_to hidden_neuron_layers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/hidden_neuron_layers_helper.rb
module HiddenNeuronLayersHelper
end

app/views/hidden_neuron_layers/_form.html.haml
= form_for @hidden_neuron_layer, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :neuron_count, :class => 'control-label'
    .controls
      = f.number_field :neuron_count, :class => 'number_field'
  .control-group
    = f.label :mind_id, :class => 'control-label'
    .controls
      = f.number_field :mind_id, :class => 'number_field'
  .control-group
    = f.label :position, :class => 'control-label'
    .controls
      = f.number_field :position, :class => 'number_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), hidden_neuron_layers_path, :class => 'btn'

app/views/hidden_neuron_layers/edit.html.haml
- model_class = HiddenNeuronLayer
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/hidden_neuron_layers/index.html.haml
- model_class = HiddenNeuronLayer
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:neuron_count)
      %th= model_class.human_attribute_name(:mind_id)
      %th= model_class.human_attribute_name(:position)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @hidden_neuron_layers.each do |hidden_neuron_layer|
      %tr
        %td= link_to hidden_neuron_layer.id, hidden_neuron_layer_path(hidden_neuron_layer)
        %td= hidden_neuron_layer.neuron_count
        %td= hidden_neuron_layer.mind_id
        %td= hidden_neuron_layer.position
        %td=l hidden_neuron_layer.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_hidden_neuron_layer_path(hidden_neuron_layer), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), hidden_neuron_layer_path(hidden_neuron_layer), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_hidden_neuron_layer_path, :class => 'btn btn-primary'

app/views/hidden_neuron_layers/new.html.haml
- model_class = HiddenNeuronLayer
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/hidden_neuron_layers/show.html.haml
- model_class = HiddenNeuronLayer
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:neuron_count) + ':'
  %br
  = @hidden_neuron_layer.neuron_count
%p
  %strong= model_class.human_attribute_name(:mind_id) + ':'
  %br
  = @hidden_neuron_layer.mind_id
%p
  %strong= model_class.human_attribute_name(:position) + ':'
  %br
  = @hidden_neuron_layer.position

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), hidden_neuron_layers_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_hidden_neuron_layer_path(@hidden_neuron_layer), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), hidden_neuron_layer_path(@hidden_neuron_layer), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'