config/routes.rb
Minds::Application.routes.draw do
  resources :hidden_neuron_layers

  resources :analyses

  get "welcome/hero"

  resources :training_data

  resources :minds

  root :to => 'welcome#hero'

end

app/models/mind.rb
class Mind < ActiveRecord::Base
  attr_accessible :description, :name
  attr_accessible :input_arity, :output_arity
  attr_accessible :hidden_neuron_layers_attributes
  has_many :hidden_neuron_layers, :order => "position"

  after_create :bootstrap
  accepts_nested_attributes_for :hidden_neuron_layers

  # array of integers which indicate desired hidden neuron structure
  #serialize :hidden_neurons, Array

  has_many :training_data
  has_many :analyses

  #
  def self.from_training_set(training_set, hidden_neurons=[3])
    mind = Mind.create(
      input_arity:  training_set.first[:input].size,
      output_arity: training_set.first[:output].size
    )

    training_set.each do |datum|
      mind.training_data.build(input: datum[:input], expected_output: datum[:output])
    end

    hidden_neurons.each_with_index do |neuron_count,position|
      mind.hidden_neuron_layers.build(position: position, neuron_count: neuron_count)
    end

    mind.save!
    mind.train
    mind
  end

  def analyze!(input)
    puts "--- about to train and analyze..."
    train
    analyze(input)
  end



  def analyze(input)
    if input.is_a? Array and input.all? { |e| e.is_a? Numeric }
      @brain.run(input)
    else
      p input
      raise "Expecting array of numbers!"
    end
  end


  def build_hidden_neuron_layers #_from_int_array
    hidden_neuron_layers.build({:position => 0, :neuron_count => input_arity})
    5.times do |n|
      hidden_neuron_layers.build({:position => n+1, :neuron_count => 2+rand(5)})
    end
    hidden_neuron_layers.build({:position => 6, :neuron_count => output_arity})
  end


  # from ruby-fann docs:
  #   max_epochs - The maximum number of epochs the training should continue
  #   epochs_between_reports - The number of epochs between printing a status report to stdout.
  #   desired_error - The desired <get_MSE> or <get_bit_fail>, depending on which stop function
  #                   is chosen by <set_train_stop_function>.
  #10000, 1000, 0.0
  def train(sample_data=training_set,max_epochs=1000,epochs_between_reports=1000,desired_error=0.0001)
    #p sample_data
    if sample_data.is_a? RubyFann::TrainData

      @brain.init_weights(sample_data)
      @brain.train_on_data(sample_data, max_epochs, epochs_between_reports, desired_error)
    else
      p sample_data
      raise "Expecting Ruby::Fann training set!"
    end
  end

  private

  def training_set
    unless training_data.all? { |data| data.input.is_a? Array and data.input.all? { |e| e.is_a? Numeric }}
      unless training_data.all? { |data| data.expected_output.is_a? Array and data.expected_output.all? { |e| e.is_a? Numeric }}
        raise "Mind#train! currently raises errors unless given numeric-valued input data for debugging purposes"
      end
    end

    input = training_data.map(&:input) # []
    output = training_data.map(&:expected_output)

    p input
    p output

    RubyFann::TrainData.new(inputs: input, desired_outputs: output)
  end

  def bootstrap
    @brain = RubyFann::Standard.new(
      num_inputs: self.input_arity,
      hidden_neurons: self.hidden_neuron_layers.map(&:neuron_count),
      num_outputs: self.output_arity
    )

    @brain.set_activation_steepness_hidden(1.0)
    @brain.set_activation_steepness_output(1.0)
    @brain.set_activation_function_hidden(:sigmoid_symmetric)
    @brain.set_activation_function_output(:sigmoid_symmetric)

    bit_fail = 0.001
    @brain.set_train_stop_function(:bit)
    @brain.set_bit_fail_limit(bit_fail)
  end
end

app/controllers/minds_controller.rb
class MindsController < ApplicationController
  # GET /minds
  # GET /minds.json
  def index
    @minds = Mind.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @minds }
    end
  end

  # GET /minds/1
  # GET /minds/1.json
  def show
    @mind = Mind.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mind }
    end
  end

  # GET /minds/new
  # GET /minds/new.json
  def new
    @mind = Mind.new(:input_arity => 3, :output_arity => 1)
    @mind.build_hidden_neuron_layers #({:position => 1, :neuron_count => 3})

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mind }
    end
  end

  # GET /minds/1/edit
  def edit
    @mind = Mind.find(params[:id])
  end

  # POST /minds
  # POST /minds.json
  def create
    @mind = Mind.new(params[:mind])

    respond_to do |format|
      if @mind.save
        format.html { redirect_to @mind, notice: 'Mind was successfully created.' }
        format.json { render json: @mind, status: :created, location: @mind }
      else
        format.html { render action: "new" }
        format.json { render json: @mind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /minds/1
  # PUT /minds/1.json
  def update
    @mind = Mind.find(params[:id])

    respond_to do |format|
      if @mind.update_attributes(params[:mind])
        format.html { redirect_to @mind, notice: 'Mind was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /minds/1
  # DELETE /minds/1.json
  def destroy
    @mind = Mind.find(params[:id])
    @mind.destroy

    respond_to do |format|
      format.html { redirect_to minds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/minds_helper.rb
module MindsHelper
end

app/views/minds/_form.html.haml
= form_for @mind, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_field :description, :class => 'text_field'
  .control-group
    = f.label :input_arity, :class => 'control-label'
    .controls
      = f.number_field :input_arity, :class => 'number_field'
  .control-group
    = f.label :output_arity, :class => 'control-label'
    .controls
      = f.number_field :output_arity, :class => 'number_field'

  #sortable.control-group
    -#.span12
    -#= f.label :hidden_neuron_layers, :class => 'control-label'
    -#.span12
    = f.fields_for :hidden_neuron_layers do |builder|
      .neuron-layer
        .well
          = builder.hidden_field :mind_id, :value => @mind.id
          .control-group
            = builder.label :neuron_count, :class => 'control-label'
            .controls
              = builder.number_field :neuron_count, :class => 'number_field input-small'
          .control-group
            = builder.label :position, :class => 'control-label'
            .controls
              = builder.number_field :position, :class => 'number_field input-small'
          -#.form-actions
          -#  = builder.submit 'Create!', :class => 'btn btn-primary'
            -#= link_to t('.cancel', :default => t("helpers.links.cancel")), hidden_neuron_layers_path, :class => 'btn'




    -#= form_for(@mind.hidden_neuron_layers) do |innerf|
    -#  %p something
    -#= form_for(@mind.hidden_neuron_layers) do |inner_form|
      .control-group
        = inner_form.label :neuron_count
        .controls
          = innter_form.number_field :output_arity, :class => 'number_field'
        = inner_form.submit

    -#%ul
    -#  - @mind.hidden_neuron_layers.each do |layer|
    -#    %li = layer.count


  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), minds_path, :class => 'btn'

app/views/minds/edit.html.haml
- model_class = Mind
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/minds/index.html.haml
- model_class = Mind
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:input_arity)
      %th= model_class.human_attribute_name(:output_arity)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @minds.each do |mind|
      %tr
        %td= link_to mind.id, mind_path(mind)
        %td= mind.name
        %td= mind.description
        %td= mind.input_arity
        %td= mind.output_arity
        %td=l mind.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_mind_path(mind), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), mind_path(mind), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_mind_path, :class => 'btn btn-primary'

app/views/minds/new.html.haml
- model_class = Mind
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/minds/show.html.haml
- model_class = Mind
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @mind.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @mind.description
%p
  %strong= model_class.human_attribute_name(:input_arity) + ':'
  %br
  = @mind.input_arity
%p
  %strong= model_class.human_attribute_name(:output_arity) + ':'
  %br
  = @mind.output_arity

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), minds_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_mind_path(@mind), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), mind_path(@mind), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'