config/routes.rb
Minds::Application.routes.draw do
  resources :hidden_neuron_layers

  resources :analyses

  get "welcome/hero"

  resources :training_data

  resources :minds

  root :to => 'welcome#hero'

end

app/controllers/analyses_controller.rb
class AnalysesController < ApplicationController
  # GET /analyses
  # GET /analyses.json
  def index
    @analyses = Analysis.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @analyses }
    end
  end

  # GET /analyses/1
  # GET /analyses/1.json
  def show
    @analysis = Analysis.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @analysis }
    end
  end

  # GET /analyses/new
  # GET /analyses/new.json
  def new
    @analysis = Analysis.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @analysis }
    end
  end

  # GET /analyses/1/edit
  def edit
    @analysis = Analysis.find(params[:id])
  end

  # POST /analyses
  # POST /analyses.json
  def create
    @analysis = Analysis.new(params[:analysis])

    respond_to do |format|
      if @analysis.save
        format.html { redirect_to @analysis, notice: 'Analysis was successfully created.' }
        format.json { render json: @analysis, status: :created, location: @analysis }
      else
        format.html { render action: "new" }
        format.json { render json: @analysis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /analyses/1
  # PUT /analyses/1.json
  def update
    @analysis = Analysis.find(params[:id])

    respond_to do |format|
      if @analysis.update_attributes(params[:analysis])
        format.html { redirect_to @analysis, notice: 'Analysis was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @analysis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /analyses/1
  # DELETE /analyses/1.json
  def destroy
    @analysis = Analysis.find(params[:id])
    @analysis.destroy

    respond_to do |format|
      format.html { redirect_to analyses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/analyses_helper.rb
module AnalysesHelper
end

app/views/analyses/_form.html.haml
= form_for @analysis, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :inputs, :class => 'control-label'
    .controls
      = f.text_area :inputs, :class => 'text_area'
  .control-group
    = f.label :output, :class => 'control-label'
    .controls
      = f.text_area :output, :class => 'text_area'
  .control-group
    = f.label :mind_id, :class => 'control-label'
    .controls
      = f.number_field :mind_id, :class => 'number_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), analyses_path, :class => 'btn'

app/views/analyses/edit.html.haml
- model_class = Analysis
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/analyses/index.html.haml
- model_class = Analysis
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:inputs)
      %th= model_class.human_attribute_name(:output)
      %th= model_class.human_attribute_name(:mind_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @analyses.each do |analysis|
      %tr
        %td= link_to analysis.id, analysis_path(analysis)
        %td= analysis.inputs
        %td= analysis.output
        %td= analysis.mind_id
        %td=l analysis.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_analysis_path(analysis), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), analysis_path(analysis), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_analysis_path, :class => 'btn btn-primary'

app/views/analyses/new.html.haml
- model_class = Analysis
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/analyses/show.html.haml
- model_class = Analysis
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:inputs) + ':'
  %br
  = @analysis.inputs
%p
  %strong= model_class.human_attribute_name(:output) + ':'
  %br
  = @analysis.output
%p
  %strong= model_class.human_attribute_name(:mind_id) + ':'
  %br
  = @analysis.mind_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), analyses_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_analysis_path(@analysis), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), analysis_path(@analysis), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'