config/routes.rb
Minds::Application.routes.draw do
  resources :hidden_neuron_layers

  resources :analyses

  get "welcome/hero"

  resources :training_data

  resources :minds

  root :to => 'welcome#hero'

end

app/controllers/training_data_controller.rb
class TrainingDataController < ApplicationController
  # GET /training_data
  # GET /training_data.json
  def index
    @training_data = TrainingDatum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @training_data }
    end
  end

  # GET /training_data/1
  # GET /training_data/1.json
  def show
    @training_datum = TrainingDatum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @training_datum }
    end
  end

  # GET /training_data/new
  # GET /training_data/new.json
  def new
    @training_datum = TrainingDatum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @training_datum }
    end
  end

  # GET /training_data/1/edit
  def edit
    @training_datum = TrainingDatum.find(params[:id])
  end

  # POST /training_data
  # POST /training_data.json
  def create
    @training_datum = TrainingDatum.new(params[:training_datum])

    respond_to do |format|
      if @training_datum.save
        format.html { redirect_to @training_datum, notice: 'Training datum was successfully created.' }
        format.json { render json: @training_datum, status: :created, location: @training_datum }
      else
        format.html { render action: "new" }
        format.json { render json: @training_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /training_data/1
  # PUT /training_data/1.json
  def update
    @training_datum = TrainingDatum.find(params[:id])

    respond_to do |format|
      if @training_datum.update_attributes(params[:training_datum])
        format.html { redirect_to @training_datum, notice: 'Training datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @training_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /training_data/1
  # DELETE /training_data/1.json
  def destroy
    @training_datum = TrainingDatum.find(params[:id])
    @training_datum.destroy

    respond_to do |format|
      format.html { redirect_to training_data_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/training_data_helper.rb
module TrainingDataHelper
end

app/views/training_data/_form.html.haml
= form_for @training_datum, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_field :description, :class => 'text_field'
  .control-group
    = f.label :mind_id, :class => 'control-label'
    .controls
      = f.number_field :mind_id, :class => 'number_field'
  .control-group
    = f.label :input, :class => 'control-label'
    .controls
      = f.text_area :input, :class => 'text_area'
  .control-group
    = f.label :expected_output, :class => 'control-label'
    .controls
      = f.text_area :expected_output, :class => 'text_area'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), training_data_path, :class => 'btn'

app/views/training_data/edit.html.haml
- model_class = TrainingDatum
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/training_data/index.html.haml
- model_class = TrainingDatum
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:mind_id)
      %th= model_class.human_attribute_name(:input)
      %th= model_class.human_attribute_name(:expected_output)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @training_data.each do |training_datum|
      %tr
        %td= link_to training_datum.id, training_datum_path(training_datum)
        %td= training_datum.name
        %td= training_datum.description
        %td= training_datum.mind_id
        %td= training_datum.input
        %td= training_datum.expected_output
        %td=l training_datum.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_training_datum_path(training_datum), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), training_datum_path(training_datum), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_training_datum_path, :class => 'btn btn-primary'

app/views/training_data/new.html.haml
- model_class = TrainingDatum
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/training_data/show.html.haml
- model_class = TrainingDatum
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @training_datum.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @training_datum.description
%p
  %strong= model_class.human_attribute_name(:mind_id) + ':'
  %br
  = @training_datum.mind_id
%p
  %strong= model_class.human_attribute_name(:input) + ':'
  %br
  = @training_datum.input
%p
  %strong= model_class.human_attribute_name(:expected_output) + ':'
  %br
  = @training_datum.expected_output

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), training_data_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_training_datum_path(@training_datum), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), training_datum_path(@training_datum), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'